language: java
cache: bundler

rvm:
  - 2.5.3

addons:
  chrome: stable

services:
  - mysql
  - docker

before_install:
  - wget -N http://chromedriver.storage.googleapis.com/74.0.3279.6/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - cd cucumber
  - bundle install
  - cd ..
  - docker build -t imhungry - < Dockerfile
  - docker run -d -p "8080":"8080" -p "8443":"8443" imhungry
  - mysql -u root < database.sql
  
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  - mvn test jacoco:report
  - cat target/jacoco-ut/jacoco.csv
  - cd cucumber
  - cucumber features/SignUpInOut/SignUpInOut.feature
  - cucumber features/Search/P2_SearchPage.feature
  - cucumber features/Result/P2_ResultsPage.feature
  - cucumber features/ManageList/P2_ManageList.feature